apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque 
data: 
  #travel_user as username 
  datasource.username: dHJhdmVsX3VzZXI=
  #27BEYOBob7 as password 
  datasource.password: MjdCRVlPQm9iNw==