apiVersion: v1
kind: Secret
metadata:
  name: mail-secrets
type: Opaque 
data: 
  #simple.travel.site.quarkus@gmail.com as username 
  mail.username: c2ltcGxlLnRyYXZlbC5zaXRlLnF1YXJrdXNAZ21haWwuY29t
  #lzgmvusaovttbxkg as password 
  mail.password: bHpnbXZ1c2FvdnR0YnhrZw==